import type { Metadata } from "next";
import { Courier_Prime, Inter } from "next/font/google";
import "./globals.css";
import Provider from "./components/Provider";
import { auth } from "@/app/api/auth/[...nextauth]/authConfig";
import { SWR } from "./components";
import Maintenance from "./components/Maintenance";
import { cookies } from "next/headers";
import { Toaster } from "sonner";


const inter = Inter({ subsets: ["latin"] });
const courierPrime = Courier_Prime({subsets: ["latin"], variable: "--font-courier-prime", weight: "700"});

export const metadata: Metadata = {
  title: "Attendance",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const maintenance = process.env.MAINTENANCE_MODE;

  if (maintenance === "on") {
    const cookieStore = await cookies();
    const key = cookieStore.get("maintenance_key") || { value: "" };
    if (key.value !== process.env.MAINTENANCE_KEY) {
      return (
        <html lang="en">
          <body className={`${inter.className} ${courierPrime.variable} bg-white`}>
            <Maintenance />
          </body>
        </html>
      );
    }
  }

  return (
    <html lang="en">
      <body className={`${inter.className} ${courierPrime.variable} bg-white`}>
        <Provider session={session}>
          <Toaster richColors />
          <SWR>{children}</SWR>
        </Provider>
      </body>
    </html>
  );
}
