import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import bcrypt from "bcrypt";

import sequlize from "@/db";
import User from "@/models/User";
import { getServerSession } from "next-auth";
import Provider from "@/app/components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Attendance",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider session={session}>{children}</Provider>
      </body>
    </html>
  );
}
