import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import Provider from "./components/Provider";
import { auth } from "./api/auth/[...nextauth]/auth";
import { SWRConfig } from "swr";
import { notFound } from "next/navigation";
import { SWR } from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Attendance",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <Provider session={session}>
          <ToastContainer />
          <SWR>{children}</SWR>
        </Provider>
      </body>
    </html>
  );
}
